### ISSUE TITLE
BatchLabs: App splited in features that are can be enabled and disabled

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchExplorer#1449]
Make the app support features that can be enabled and disabled which will not show disabled features.

Examples Features
* `pool`
    * `pool.create`
    * `pool.patch`
* `certificate`
* `gallery`

## Configuration file 
```yaml
{
    "certificate": true,
    "pool": {
        "add": true
    },
    "job": {
        "add": true,
        "view": true
    }
}
```

## Service
```ts
class WorkspaceService { 
    public currentWorkspace: Observable<Workspace>
    selectWorkspace(workspaceId: string);

    public isFeatureEnabled(feature: string): boolean;
    public isFeatureDisabled(feature: string): boolean;
}
```

## Model
```ts
class Workspace {
// Takes the inputs from a file an process

    public isFeatureEnabled(feature: string): boolean;
    public isFeatureDisabled(feature: string): boolean;
}
```

### Directive
Have a directive to use in the templates to make it easier to enable a feature

Name `feature`, `featureEnabled`, `featureOn`?
```html
<div *featureOn="job.view">

</div>


<div *featureOff="job.add">

</div>
```

**Comment by ascobie** [comment]
How about something like this as a first go? completely unsure, but need a way to hide top level navigation as well. I like the separation between viewing and modifying. Though as the first cut, maybe we wont worry about the modification bits at all as these are more permissions based, and expand it into more feature areas.

## Configuration file 
```yaml
{
    "job": {
        "navigate": true,
        "view": {
            "graphs": true,
            "statistics": true,
            "tags": true,
            "asJson": false
        },
        "maintain": {
            "add": true,
            "delete": true,
            "edit": true,
            "addTask": true,
            "terminate": true,
            "clone": true,
            "schedule": true,
            "export": true,
            "pin": true,
        }
    },
    "schedule": {
        "navigate": false,
        "view": {
        },
        "maintain": {
        }
    }
    "pool": {
        "navigate": true,
        "view": {
            "cost": true,
            "tags": true,
            "asJson": true,
            "availableNodes": false,
            "runningTasks": true,
            "appInsights": false,
            "nodes": true,
        },
        "maintain": {
            "add": true,
            "delete": true,
            "addJob": true,
            "resize": true,
            "clone": true,
            "export": true,
            "pin": true,
        }
    },
    "package": {
        "navigate": false,
        "view": {
        },
        "maintain": {
            "add": true,
            "delete": true,
            "addVersion": true,
            "edit": true,
            "pin": true,
        }
    },
    "certificate": {
        "navigate": false,
        "view": {
        },
        "maintain": {
            "add": true,
            "delete": true,
            "reactivate": true,
            "export": false,
            "pin": true,
        }
    },
    "data": {
        "navigate": true,
        "view": {
            "fileGroups": true,
            "containers": true,
            "accounts": false,
        },
        "maintain": {
            "addContainer": true,
            "deleteContainer": true,
            "addFileGroup": true,
            "deleteFileGroup": true,
            "modify": true,
            "download": true,
            "pin": true,
        }
    }
}
```
